# -*- coding: utf-8 -*-
##############################################################################
#
#    OmniaSolutions, Open Source Management Solution
#    Copyright (C) 2010-2026 OmniaSolutions (<http://www.omniasolutions.eu>).
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
{
    "name": "PLM Demo Data",
    "version": "19.0.1.0.0",
    "author": "OmniaSolutions",
    "website": "https://odooplm.omniasolutions.website",
    "category": "Manufacturing/Product Lifecycle Management (PLM)",
    "sequence": 20,
    "license": "AGPL-3",
    "summary": """
    A populated PLM environment to look at, instead of an empty one.

    Installs a small mechanical product with its multi-level bills of material,
    a spare part BOM, engineering documents in STEP, 3MF, DXF and PDF, document
    relations, product images, 3D markups and the chatter that goes with them.
    """,
    "description": """
PLM Demo Data
=============

Installing `plm` gives you a working PLM with nothing in it. This module fills it
with a complete little product: **LSU-100**, a linear shaft support unit made of a
base plate, two bearing units and a shaft.

* 12 parts over three BOM levels, with materials and weights taken from the solids
* a spare part BOM for each assembly, whose rows keep the position they carry on
  the drawing: the balloon on the sheet is the itemnum of the BOM line
* 29 documents: a 3MF and a STEP for every part, DXF drawing sheets for the
  machined ones and for the two assemblies, each carrying its printable PDF in
  the printout field, all with previews
* ballooned assembly sheets with a parts list, flagged for the Spare Parts Manual
* the document structure a CAD upload produces: the STEP model at the top, its
  3MF viewer file and its 2D sheet hanging from it, assembly to component
* two 3D markups on the top assembly, with the chatter messages that go with them

The geometry is generated by ``tools/generate_demo_geometry.py`` using cadquery and
ezdxf, so everything published here belongs to OmniaSolutions and carries the same
AGPL-3 licence as the module. No third party CAD model is redistributed.

Everything is created through the ORM at install time, with proper external ids,
so uninstalling the module removes the demo data again.

Intended for evaluation, demonstrations and training. Do not install it on a
production database.
""",
    "depends": [
        "plm",
        "plm_spare",
        "plm_web_3d",
    ],
    "data": [],
    "post_init_hook": "post_init_hook",
    "uninstall_hook": "uninstall_hook",
    "installable": True,
    "application": False,
    "auto_install": False,
}
