# -*- coding: utf-8 -*-
##############################################################################
#
#    OmniaSolutions, ERP-PLM-CAD Open Source Solutions
#    Copyright (C) 2011-2026 https://OmniaSolutions.website
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU Affero General Public License as
#    published by the Free Software Foundation, either version 3 of the
#    License, or (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU Affero General Public License for more details.
#
#    You should have received a copy of the GNU Affero General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
#
##############################################################################
"""Turning the MCP tools into tools of Odoo's own agent.

Both worlds want the same three things — a name, a description and a schema of
the arguments — and the registry already holds all three. So nothing here is
written by hand: the server actions are generated from ``_tool_specs()``, and a
tool added to the suite tomorrow appears in the chat without this module being
touched.

Three details of the Odoo side shape the code below, all read from the ai module
rather than assumed:

the tool's name, as the model sees it, is the *external id* of the action
(ir_actions_server.py:206), so each one is registered under an id equal to the
tool name — otherwise the model would be offered "action_412";

a code action returns to the model whatever it leaves in ``ai['result']``
(ir_actions_server.py:361), and setting ``action`` instead makes it interactive,
which the agent refuses;

every declared argument reaches the code as a variable, filled with None when
the model omitted it (validators.py:51). That is why the generated call passes
them all and lets _call_tool drop the empty ones.

The action runs as the user, not in sudo — env is rebuilt with su=False before
the code is evaluated — so the same record rules that bound the MCP server bind
the chat.
"""
import json
import logging

from odoo import api, models

_logger = logging.getLogger(__name__)

MODULE = "plm_mcp_odoo_ai"
TOPIC_XMLID = "plm_mcp_odoo_ai.ai_topic_plm"

# The action's code is generated, so it is written once here rather than
# scattered through a template file: read it as "hand the arguments to the
# registry and give back what it answers".
CODE_TEMPLATE = """# Generated by plm_mcp_odoo_ai — do not edit, it is rewritten on update.
ai['result'] = env['plm.mcp.tool']._call_tool(%(name)r, %(arguments)s)
"""


class PlmMcpTool(models.AbstractModel):
    _inherit = "plm.mcp.tool"

    @api.model
    def _sync_odoo_ai_tools(self):
        """Create or refresh one server action per declared tool.

        Idempotent by external id: running it again updates what changed and
        leaves the rest alone, which is what makes it safe to call on every
        module update.
        """
        specs = self._tool_specs()
        model = self.env["ir.model"]._get("plm.mcp.tool")
        actions = self.env["ir.actions.server"]

        for tool_name, (_method_name, spec) in specs.items():
            values = {
                "name": tool_name,
                "model_id": model.id,
                "state": "code",
                "code": self._odoo_ai_code(tool_name, spec),
                "use_in_ai": True,
                # The description is the whole point of the exercise: it is what
                # tells the model when to reach for this tool, and it is already
                # written for exactly that purpose.
                "ai_tool_description": spec["description"],
                "ai_tool_schema": json.dumps(spec["inputSchema"], indent=2),
            }
            action = self.env.ref("%s.%s" % (MODULE, tool_name),
                                  raise_if_not_found=False)
            if action:
                action.write(values)
            else:
                action = self.env["ir.actions.server"].create(values)
                self.env["ir.model.data"]._update_xmlids([{
                    # The external id *is* the tool name the model will call.
                    "xml_id": "%s.%s" % (MODULE, tool_name),
                    "record": action,
                    "noupdate": False,
                }])
            actions |= action

        topic = self.env.ref(TOPIC_XMLID, raise_if_not_found=False)
        if topic:
            topic.sudo().tool_ids = [(6, 0, actions.ids)]
        _logger.info("plm_mcp_odoo_ai: %s tools published to the Odoo agent",
                     len(actions))
        return actions

    @api.model
    def _odoo_ai_code(self, tool_name, spec):
        """The body of the generated action.

        Every declared argument is passed by name. They are always defined —
        Odoo fills the missing ones with None — and _call_tool drops the empty
        ones, so an argument the model left out behaves as if it had never been
        mentioned rather than overriding a default with None.
        """
        properties = spec["inputSchema"]["properties"]
        if properties:
            arguments = "{%s}" % ", ".join(
                "%r: %s" % (name, name) for name in sorted(properties))
        else:
            arguments = "{}"
        return CODE_TEMPLATE % {"name": tool_name, "arguments": arguments}
