#!/usr/bin/env python3
"""Regenerate aaa_requirements.txt from the modules' manifests.

The python packages OdooPLM needs are declared, module by module, in the
``external_dependencies`` key of every ``__manifest__.py``. That is the only
place a developer touches when a module grows a new dependency. This script
reads all of them and writes the repository requirements file, so the file
cannot drift away from what the modules actually declare — which is exactly
what happened before it existed: ``googletrans`` and ``polib`` were declared by
plm_auto_translator and missing from the file, while ``cadquery`` was listed
twice with two contradictory specifications.

Manifests carry no versions, on purpose: an Odoo manifest states *what* a module
imports, not *which release* of it works. The versions live in
``scripts/requirements_pins.txt``:

* a pin whose name matches a declared dependency overrides that line
  (``matplotlib`` declared by the manifest, ``matplotlib==3.8.4`` written out);
* a pin whose name matches nothing declared is an indirect constraint — a
  transitive package that only resolves at a given version — and is written in
  its own section at the end.

The same manifests drive ``extras_require`` in ``setup.py`` through
``compute_extras()``, so the wheel's optional dependencies and the requirements
file are always the same data.

Usage::

    python3 scripts/sync_requirements.py            # rewrite the file
    python3 scripts/sync_requirements.py --check    # only report drift
"""

from __future__ import annotations

import argparse
import ast
import os
import re
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)

REQUIREMENTS = os.path.join(ROOT, "aaa_requirements.txt")
PINS = os.path.join(HERE, "requirements_pins.txt")

HEADER = """\
# Generated by scripts/sync_requirements.py — do not edit by hand.
#
# Declare a package in the external_dependencies of the module that imports it,
# pin its version in scripts/requirements_pins.txt, then run:
#
#     python3 scripts/sync_requirements.py
#
# Installing this file gives you every optional module's dependency. For a
# lighter install, take only the section you need.
"""

# Which modules make up each optional install. A module that declares
# dependencies and is named in no group still lands in "full" — and the script
# says so, so the group list cannot silently fall behind the modules.
EXTRA_GROUPS = {
    "cad": ["plm_automated_convertion"],
    "pack": ["plm_pack_and_go"],
    "translate": ["plm_auto_translator"],
}

# PEP 503 normalisation: Numpy-STL, numpy_stl and numpy-stl are one package.
_CANON = re.compile(r"[-_.]+")

# A requirement line starts with the distribution name, then a specifier
# (==, >=, ~=, …), an extras bracket, or " @ " for a direct reference.
_NAME = re.compile(r"^\s*([A-Za-z0-9][A-Za-z0-9._-]*)\s*(?:[\[<>=!~;@]|$)")


def canonical(name):
    return _CANON.sub("-", name).lower()


def requirement_name(line):
    """The distribution name a requirement line installs, or None."""
    match = _NAME.match(line)
    return canonical(match.group(1)) if match else None


def read_manifest(path):
    """Return the manifest dict, or None if the file holds no dict literal."""
    with open(path, encoding="utf-8") as fobj:
        tree = ast.parse(fobj.read())
    for node in tree.body:
        if isinstance(node, ast.Expr) and isinstance(node.value, ast.Dict):
            return ast.literal_eval(node.value)
    return None


def iter_modules(root=ROOT):
    """Yield (module_name, manifest) for every addon in the repository."""
    for name in sorted(os.listdir(root)):
        if name.startswith("."):
            continue
        manifest_path = os.path.join(root, name, "__manifest__.py")
        if not os.path.isfile(manifest_path):
            continue
        manifest = read_manifest(manifest_path)
        if manifest is not None:
            yield name, manifest


def collect_dependencies(root=ROOT):
    """Map canonical package name -> {declared name, modules that need it}."""
    found = {}
    for module, manifest in iter_modules(root):
        external = manifest.get("external_dependencies") or {}
        for package in external.get("python") or []:
            entry = found.setdefault(
                canonical(package), {"name": package, "modules": []}
            )
            entry["modules"].append(module)
    return found


def read_pins(path=PINS):
    """Map canonical package name -> full requirement line."""
    pins = {}
    if not os.path.isfile(path):
        return pins
    with open(path, encoding="utf-8") as fobj:
        for raw in fobj:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            name = requirement_name(line)
            if name is None:
                sys.stderr.write(
                    "warning: cannot read a package name from pin {!r}, "
                    "ignored\n".format(line)
                )
                continue
            pins[name] = line
    return pins


def compute_extras(root=ROOT):
    """Map extra name -> sorted requirement lines, for setup.py.

    Groups come from EXTRA_GROUPS; "full" is every declared dependency.

    Direct references (``name @ git+https://…``) are reduced to the bare name:
    PyPI refuses a distribution whose Requires-Dist carries a URL, so a pip
    install of the wheel takes whatever release of that package is on PyPI.
    The URL stays in aaa_requirements.txt, which is what a developer installs.
    """
    declared = collect_dependencies(root)
    pins = read_pins()

    def line_for(canonical_name):
        pin = pins.get(canonical_name)
        if pin is None or "@" in pin.split(";")[0]:
            return declared[canonical_name]["name"]
        return pin

    extras = {}
    for extra, modules in EXTRA_GROUPS.items():
        names = [
            canonical_name
            for canonical_name, entry in declared.items()
            if set(entry["modules"]) & set(modules)
        ]
        if names:
            extras[extra] = sorted(line_for(name) for name in names)
    extras["full"] = sorted(line_for(name) for name in declared)
    return extras


def render(root=ROOT):
    """Build the whole content of aaa_requirements.txt."""
    declared = collect_dependencies(root)
    pins = read_pins()

    grouped = set()
    for modules in EXTRA_GROUPS.values():
        grouped.update(modules)
    ungrouped = sorted(
        {
            module
            for entry in declared.values()
            for module in entry["modules"]
            if module not in grouped
        }
    )

    lines = [HEADER]
    for extra in sorted(EXTRA_GROUPS):
        members = [
            (canonical_name, entry)
            for canonical_name, entry in declared.items()
            if set(entry["modules"]) & set(EXTRA_GROUPS[extra])
        ]
        if not members:
            continue
        lines.append("# {}: {}".format(extra, ", ".join(sorted(EXTRA_GROUPS[extra]))))
        for canonical_name, entry in sorted(members):
            lines.append(pins.get(canonical_name, entry["name"]))
        lines.append("")

    if ungrouped:
        lines.append("# other modules: {}".format(", ".join(ungrouped)))
        for canonical_name, entry in sorted(declared.items()):
            if set(entry["modules"]) & set(ungrouped):
                lines.append(pins.get(canonical_name, entry["name"]))
        lines.append("")

    indirect = sorted(name for name in pins if name not in declared)
    if indirect:
        lines.append(
            "# indirect constraints — pinned in scripts/requirements_pins.txt,"
        )
        lines.append("# declared by no manifest because no module imports them.")
        for name in indirect:
            lines.append(pins[name])
        lines.append("")

    return "\n".join(lines).rstrip("\n") + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="exit non-zero if the file is out of date, without writing it",
    )
    # pre-commit passes the changed filenames; the script always reads every
    # manifest, so they are accepted and ignored.
    parser.add_argument("filenames", nargs="*", help=argparse.SUPPRESS)
    args = parser.parse_args(argv)

    expected = render()
    current = ""
    if os.path.isfile(REQUIREMENTS):
        with open(REQUIREMENTS, encoding="utf-8") as fobj:
            current = fobj.read()

    if current == expected:
        return 0

    if args.check:
        sys.stderr.write(
            "aaa_requirements.txt is out of date.\n"
            "Run: python3 scripts/sync_requirements.py\n"
        )
        return 1

    with open(REQUIREMENTS, "w", encoding="utf-8") as fobj:
        fobj.write(expected)

    # Stage it, the way the version bump hook does, so the regenerated file is
    # part of the commit the developer is about to retry.
    subprocess.run(["git", "add", REQUIREMENTS], cwd=ROOT, check=False)
    sys.stderr.write(
        "aaa_requirements.txt regenerated from the manifests and staged. "
        "Review it, then commit again.\n"
    )
    return 1


if __name__ == "__main__":
    sys.exit(main())
